apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gfdc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gfdc
    app.kubernetes.io/part-of: byoc-app-zdxy
  name: gfdc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: gfdc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: gfdc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-zerh-tenant/byoc-app-zdxy/gfdc@sha256:19869887edc95bc196b00b1e385e3261aee542acae08a258a7d8ad0b29c582db
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
